"""Add resources and resource_link to courses

Revision ID: 65e7d6556232
Revises: a9873da45a3c
Create Date: 2025-05-19 04:52:56.012616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65e7d6556232'
down_revision = 'a9873da45a3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resources', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('resource_link', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('resource_link')
        batch_op.drop_column('resources')

    # ### end Alembic commands ###
