"""Add is_live field to LiveLesson

Revision ID: b876501cb31b
Revises: 95a2d412527e
Create Date: 2025-05-22 05:20:19.780043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b876501cb31b'
down_revision = '95a2d412527e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('live_lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_live', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('live_lesson', schema=None) as batch_op:
        batch_op.drop_column('is_live')

    # ### end Alembic commands ###
