"""Add level and target_level fields

Revision ID: bb557b58b69c
Revises: 65e7d6556232
Create Date: 2025-05-21 08:45:27.665930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb557b58b69c'
down_revision = '65e7d6556232'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_level', sa.String(length=50), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('level')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('target_level')

    # ### end Alembic commands ###
